// Generated by CoffeeScript 1.4.0
(function() {
  var Background, textarea;

  textarea = document.getElementById('textarea');

  Background = {
    receive_message: function(request, sender, respond) {
      console.log("from the extension", request);
      if (!request.command) {
        throw 'No Command given.';
      }
      Background.request = request;
      Background.sender = sender;
      Background.respond = respond;
      return Background[request.command]();
    },
    copy: function() {
      if (this.request.content === '') {
        this.respond({
          status: 'Empty string given.'
        });
        return;
      }
      textarea.value = this.request.content;
      textarea.select();
      return this.respond({
        status: document.execCommand('Copy')
      });
    },
    track: function() {
      _gaq.push(['_trackEvent', this.request.noun, this.request.verb]);
      return this.respond({
        status: "Tracking " + this.request.noun + " " + this.request.verb
      });
    }
  };

  chrome.extension.onMessage.addListener(Background.receive_message);

}).call(this);
