// Generated by CoffeeScript 1.4.0
(function() {

  $(function() {
    GTalkSyntax.data_collection_option(function(value) {
      if (value == null) {
        value = 'localhost:3000';
      }
      if (value === 'on' || value === 'off') {
        return $("option[value=" + value + "]").attr('selected', 'selected');
      } else {
        $("option[value=custom]").attr('selected', 'selected');
        return $('#collection_custom_url').val(value).show();
      }
    });
    GTalkSyntax.auto_detect_option(function(value) {
      if (value == null) {
        value = false;
      }
      if (value) {
        return $('#auto_detect_input').check();
      }
    });
    return $('figure.kudo.kudoable').kudoable();
  });

  $(document).on('change', '#collection_method_input, #collection_custom_url', function() {
    var value;
    value = $('#collection_method_input').val();
    GTalkSyntax.track("Set " + value, 'Data Collection');
    if (value === 'custom') {
      $('#collection_custom_url').show();
      value = $('#collection_custom_url').val();
    } else {
      $('#collection_custom_url').hide();
    }
    return GTalkSyntax.data_collection_option(value, function(value) {
      return $('#collection_method_status').html("Saved: " + value);
    });
  });

  $(document).on('change', '#auto_detect_input', function() {
    var is_enabled;
    is_enabled = $('#auto_detect_input').is_checked();
    GTalkSyntax.auto_detect_option(is_enabled, function(value) {
      return $('#auto_detect_status').html("Saved: " + value);
    });
    if (is_enabled) {
      return GTalkSyntax.track('Enable', 'Auto detection');
    } else {
      return GTalkSyntax.track('Disable', 'Auto detection');
    }
  });

}).call(this);
